// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCuweSvprjPfAUkVhnE7wUx4FJd0Pht0kE',
    appId: '1:88126613710:web:2223a4d30a7b3622efc89f',
    messagingSenderId: '88126613710',
    projectId: 'fedesie-1',
    authDomain: 'fedesie-1.firebaseapp.com',
    storageBucket: 'fedesie-1.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDyzfhUywn86OPOUzq-NgsuXHW9t55XcpI',
    appId: '1:88126613710:android:f4684805a4ffd395efc89f',
    messagingSenderId: '88126613710',
    projectId: 'fedesie-1',
    storageBucket: 'fedesie-1.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyARydrlqQs-IohKYN19b0qjONeawlFcS1I',
    appId: '1:88126613710:ios:b3a9c91f70e5dfcdefc89f',
    messagingSenderId: '88126613710',
    projectId: 'fedesie-1',
    storageBucket: 'fedesie-1.appspot.com',
    iosBundleId: 'com.example.fedesieClientApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyARydrlqQs-IohKYN19b0qjONeawlFcS1I',
    appId: '1:88126613710:ios:c7bc618a293a6914efc89f',
    messagingSenderId: '88126613710',
    projectId: 'fedesie-1',
    storageBucket: 'fedesie-1.appspot.com',
    iosBundleId: 'com.example.fedesieClientApp.RunnerTests',
  );
}
